### ISSUE TITLE
Usability improvement: input for general search 

### ISSUE THREAD

**Issue by herby** [amber-smalltalk/helios#14]
<a href="https://github.com/sebastianconcept"><img src="https://avatars.githubusercontent.com/u/475508?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sebastianconcept](https://github.com/sebastianconcept)**
_Monday Apr 14, 2014 at 13:05 GMT_
_Originally opened as https://github.com/amber-smalltalk/amber/issues/955_

----

One of the rockstar features of the legacy IDE was its general search input.

In one shot you get: implementors, senders, Class references, strings and symbols

That's actually better than any known Smalltalk IDE out there.

Is "your little Google" right there in your smalltalk code.

And who isn't used to fallback to Google/search engines when searching for the next thing to do?

Is an opportunity too good to be missed.

Maybe we can borrow some real state from the tabs bar at the right? and access its focus with cmd-f or something like that?

Like in this image?

![heliossearchinput](https://cloud.githubusercontent.com/assets/475508/2695342/ae17b89a-c3d4-11e3-8853-e2ae9dad5d49.png)

**Comment by NicolasPetton** [comment]
Done in commit 4a3d0df
