### ISSUE TITLE
Double click opens two windows

### ISSUE THREAD

**Issue by blakemcbride** [amber-smalltalk/helios#54]
Greetings,

When running the textinput example, clicking on "Do Something" causes Helios to bring up an inspector.  Cool.  The problem is, if I double-click on "element" in order to inspect it, I get _two_ new inspector windows on the same "element".  Shouldn't I only get one new window?

Thanks.

Blake

**Comment by herby** [comment]
No. You just sent inspect message to it and it did its work. New Inspector window may show newer state, for example.

Blake McBride wrote:
