### ISSUE TITLE
Inspecting something not highlighted causes error

### ISSUE THREAD

**Issue by blakemcbride** [amber-smalltalk/helios#55]
While browsing a class, I put my cursor on the middle of the word "Widget".  I then clicked on InspectIt.  I get:  "Widget does not understand #subclass:", with Abandon & Debug buttons.

However if I _select the whole word_ "Widget" and click on InspectIt, it does as expected.

If the user forgets to select what they want to inspect perhaps the InspectIt button should create a popup that says: "nothing selected".

**Comment by herby** [comment]
It's a feature. Non-selected means do it with a current line.
